stages:
  - stage: macOS_latest
    displayName: 'macOS-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'macOS-latest'
    jobs:
      - job: Restore
        displayName: 'Restore'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Restore --skip'
      - job: Compile
        displayName: 'Compile'
        dependsOn: [ Restore ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Compile --skip'
      - job: Test
        displayName: 'Test'
        dependsOn: [ Compile ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Test --skip'
      - job: PublishCoverage
        displayName: 'PublishCoverage'
        dependsOn: [ Test ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'PublishCoverage --skip'
  - stage: windows_latest
    displayName: 'windows-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: Restore
        displayName: 'Restore'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Restore --skip'
      - job: Compile
        displayName: 'Compile'
        dependsOn: [ Restore ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Compile --skip'
      - job: Test
        displayName: 'Test'
        dependsOn: [ Compile ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Test --skip'
      - job: PublishCoverage
        displayName: 'PublishCoverage'
        dependsOn: [ Test ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'PublishCoverage --skip'
  - stage: ubuntu_latest
    displayName: 'ubuntu-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Restore
        displayName: 'Restore'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Restore --skip'
      - job: Compile
        displayName: 'Compile'
        dependsOn: [ Restore ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Compile --skip'
      - job: Test
        displayName: 'Test'
        dependsOn: [ Compile ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Test --skip'
      - job: PublishCoverage
        displayName: 'PublishCoverage'
        dependsOn: [ Test ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'PublishCoverage --skip'
