stages:
  - stage: windows_latest
    displayName: 'windows-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: Nuke
        displayName: 'Nuke'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
  - stage: windows_latest
    displayName: 'macOS-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'macOS-latest'
    jobs:
      - job: Restore
        displayName: 'Restore'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
  - stage: windows_latest
    displayName: 'ubuntu-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Restore
        displayName: 'Restore'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'